// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkK4XhU-Y3NPz619zrpj2X7Pe2-V4HURo',
    appId: '1:506712134074:web:4f960cb53778d781420d83',
    messagingSenderId: '506712134074',
    projectId: 'syllabuddy-5f15a',
    authDomain: 'syllabuddy-5f15a.firebaseapp.com',
    storageBucket: 'syllabuddy-5f15a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpp1idlXuFExfK_Rv-58j9dUNo_-t-h4',
    appId: '1:506712134074:android:0795e10b9933d7e5420d83',
    messagingSenderId: '506712134074',
    projectId: 'syllabuddy-5f15a',
    storageBucket: 'syllabuddy-5f15a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYtDCEbkU9jYd4rmUZ1jA1w0KCc3MGbWE',
    appId: '1:506712134074:ios:3028b71f0993c3f5420d83',
    messagingSenderId: '506712134074',
    projectId: 'syllabuddy-5f15a',
    storageBucket: 'syllabuddy-5f15a.firebasestorage.app',
    iosBundleId: 'com.example.syllabuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYtDCEbkU9jYd4rmUZ1jA1w0KCc3MGbWE',
    appId: '1:506712134074:ios:3028b71f0993c3f5420d83',
    messagingSenderId: '506712134074',
    projectId: 'syllabuddy-5f15a',
    storageBucket: 'syllabuddy-5f15a.firebasestorage.app',
    iosBundleId: 'com.example.syllabuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkK4XhU-Y3NPz619zrpj2X7Pe2-V4HURo',
    appId: '1:506712134074:web:f2e25b5e89dac254420d83',
    messagingSenderId: '506712134074',
    projectId: 'syllabuddy-5f15a',
    authDomain: 'syllabuddy-5f15a.firebaseapp.com',
    storageBucket: 'syllabuddy-5f15a.firebasestorage.app',
  );
}
